### ISSUE TITLE
Don't enable cors this way

### ISSUE THREAD

**Issue by aric87** [chieakiba/oinkster#2]
https://github.com/chieakiba/oinkster/blob/master/server/app.js#L20

You're opening your API up to anyone and everyone that wants to connect to it. That means anyone who wants to send an email can post to your server, and send an email. You should limit where the requests are allowed from. 

Checkout this plugin:  https://github.com/expressjs/cors#configuring-cors-w-dynamic-origin

**Comment by chieakiba** [comment]
Thanks for letting me know about that! I added that piece of code so only the whitelisted domain can do a post request.
